In [2]:
import pandas as pd 

df = pd.read_csv("diabetic_data.csv")
print(df.shape)
df.head()

(101766, 50)

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [4]:
df = pd.read_csv("../data/diabetic_data.csv")

In [5]:
df = pd.read_csv("../data/diabetic_data.csv")
print(df.shape)
df.head()

(101766, 50)

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 50 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   encounter_id              101766 non-null  int64
 1   patient_nbr               101766 non-null  int64
 2   race                      101766 non-null  str
 3   gender                    101766 non-null  str
 4   age                       101766 non-null  str
 5   weight                    101766 non-null  str
 6   admission_type_id         101766 non-null  int64
 7   discharge_disposition_id  101766 non-null  int64
 8   admission_source_id       101766 non-null  int64
 9   time_in_hospital          101766 non-null  int64
 10  payer_code                101766 non-null  str
 11  medical_specialty         101766 non-null  str
 12  num_lab_procedures        101766 non-null  int64
 13  num_procedures            101766 non-null  int64
 14  num_medications           101766 non-null  int64
 15  number_outpatient         101766 non-null  int64
 16  number_emergency          101766 non-null  int64
 17  number_inpatient          101766 non-null  int64
 18  diag_1                    101766 non-null  str
 19  diag_2                    101766 non-null  str
 20  diag_3                    101766 non-null  str
 21  number_diagnoses          101766 non-null  int64
 22  max_glu_serum             5346 non-null    str
 23  A1Cresult                 17018 non-null   str
 24  metformin                 101766 non-null  str
 25  repaglinide               101766 non-null  str
 26  nateglinide               101766 non-null  str
 27  chlorpropamide            101766 non-null  str
 28  glimepiride               101766 non-null  str
 29  acetohexamide             101766 non-null  str
 30  glipizide                 101766 non-null  str
 31  glyburide                 101766 non-null  str
 32  tolbutamide               101766 non-null  str
 33  pioglitazone              101766 non-null  str
 34  rosiglitazone             101766 non-null  str
 35  acarbose                  101766 non-null  str
 36  miglitol                  101766 non-null  str
 37  troglitazone              101766 non-null  str
 38  tolazamide                101766 non-null  str
 39  examide                   101766 non-null  str
 40  citoglipton               101766 non-null  str
 41  insulin                   101766 non-null  str
 42  glyburide-metformin       101766 non-null  str
 43  glipizide-metformin       101766 non-null  str
 44  glimepiride-pioglitazone  101766 non-null  str
 45  metformin-rosiglitazone   101766 non-null  str
 46  metformin-pioglitazone    101766 non-null  str
 47  change                    101766 non-null  str
 48  diabetesMed               101766 non-null  str
 49  readmitted                101766 non-null  str
dtypes: int64(13), str(37)
memory usage: 38.8 MB

In [7]:
df.isna().sum().sort_values(ascending=False).head(20)

max_glu_serum               96420
A1Cresult                   84748
race                            0
gender                          0
age                             0
weight                          0
admission_type_id               0
discharge_disposition_id        0
admission_source_id             0
time_in_hospital                0
payer_code                      0
medical_specialty               0
num_lab_procedures              0
num_procedures                  0
num_medications                 0
number_outpatient               0
encounter_id                    0
patient_nbr                     0
number_inpatient                0
number_emergency                0
dtype: int64

In [8]:
( df == "?").sum().sort_values(ascending=False).head(20)

weight                      98569
medical_specialty           49949
payer_code                  40256
race                         2273
diag_3                       1423
diag_2                        358
diag_1                         21
admission_type_id               0
patient_nbr                     0
encounter_id                    0
time_in_hospital                0
admission_source_id             0
num_lab_procedures              0
num_procedures                  0
num_medications                 0
discharge_disposition_id        0
gender                          0
age                             0
number_inpatient                0
number_emergency                0
dtype: int64

In [9]:
df = df.replace("?", pd.NA)

In [10]:
df.isna().sum().sort_values(ascending=False).head(20)

weight                      98569
max_glu_serum               96420
A1Cresult                   84748
medical_specialty           49949
payer_code                  40256
race                         2273
diag_3                       1423
diag_2                        358
diag_1                         21
patient_nbr                     0
time_in_hospital                0
admission_source_id             0
num_lab_procedures              0
encounter_id                    0
admission_type_id               0
discharge_disposition_id        0
gender                          0
age                             0
number_inpatient                0
number_emergency                0
dtype: int64

In [11]:
df["is_readmitted_30"] = df["readmitted"].apply(lambda x: 1 
    if x == "<30" else 0)
df["is_readmitted_30"].value_counts()

is_readmitted_30
0    90409
1    11357
Name: count, dtype: int64

In [12]:
cols_to_drop = ["weight", "payer_code", "medical_specialty"]

df = df.drop(columns=cols_to_drop, errors="ignore")

In [13]:
df.columns.tolist()

['encounter_id',
 'patient_nbr',
 'race',
 'gender',
 'age',
 'admission_type_id',
 'discharge_disposition_id',
 'admission_source_id',
 'time_in_hospital',
 'num_lab_procedures',
 'num_procedures',
 'num_medications',
 'number_outpatient',
 'number_emergency',
 'number_inpatient',
 'diag_1',
 'diag_2',
 'diag_3',
 'number_diagnoses',
 'max_glu_serum',
 'A1Cresult',
 'metformin',
 'repaglinide',
 'nateglinide',
 'chlorpropamide',
 'glimepiride',
 'acetohexamide',
 'glipizide',
 'glyburide',
 'tolbutamide',
 'pioglitazone',
 'rosiglitazone',
 'acarbose',
 'miglitol',
 'troglitazone',
 'tolazamide',
 'examide',
 'citoglipton',
 'insulin',
 'glyburide-metformin',
 'glipizide-metformin',
 'glimepiride-pioglitazone',
 'metformin-rosiglitazone',
 'metformin-pioglitazone',
 'change',
 'diabetesMed',
 'readmitted',
 'is_readmitted_30']

In [14]:
analysis_cols = [
    "encounter_id",
    "patient_nbr",
    "race",
    "gender",
    "age",
    "admission_type_id",
    "discharge_disposition_id",
    "time_in_hospital",
    "num_lab_procedures",
    "num_procedures",
    "num_medications",
    "number_outpatient",
    "number_emergency",
    "number_inpatient",
    "diag_1",
    "A1Cresult",
    "insulin",
    "diabetesMed",
    "readmitted",
    "is_readmitted_30"
]

analysis_df = df[analysis_cols].copy()
print(analysis_df.shape)
analysis_df.head()

(101766, 20)

,encounter_id,patient_nbr,race,gender,age,admission_type_id,discharge_disposition_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,A1Cresult,insulin,diabetesMed,readmitted,is_readmitted_30
0,2278392,8222157,Caucasian,Female,[0-10),6,25,1,41,0,1,0,0,0,250.83,NaN,No,No,NO,0
1,149190,55629189,Caucasian,Female,[10-20),1,1,3,59,0,18,0,0,0,276,NaN,Up,Yes,>30,0
2,64410,86047875,AfricanAmerican,Female,[20-30),1,1,2,11,5,13,2,0,1,648,NaN,No,Yes,NO,0
3,500364,82442376,Caucasian,Male,[30-40),1,1,2,44,1,16,0,0,0,8,NaN,Up,Yes,NO,0
4,16680,42519267,Caucasian,Male,[40-50),1,1,1,51,0,8,0,0,0,197,NaN,Steady,Yes,NO,0

In [17]:
# Overall 30 Day readmission rate.

In [15]:
analysis_df["is_readmitted_30"].mean()

np.float64(0.11159915885462728)

In [18]:
#Readmission counts

In [16]:
analysis_df["is_readmitted_30"].value_counts()

is_readmitted_30
0    90409
1    11357
Name: count, dtype: int64

In [19]:
#Average length of stay by readmission.

In [20]:
analysis_df.groupby("is_readmitted_30")["time_in_hospital"].mean()

is_readmitted_30
0    4.349224
1    4.768249
Name: time_in_hospital, dtype: float64

In [21]:
#Average number of medications by readmission.

In [22]:
analysis_df.groupby("is_readmitted_30")["num_medications"].mean()

is_readmitted_30
0    15.911137
1    16.903143
Name: num_medications, dtype: float64

In [23]:
#Average number of emergency visits by readmission. 
analysis_df.groupby("is_readmitted_30")["number_emergency"].mean()

is_readmitted_30
0    0.177803
1    0.357313
Name: number_emergency, dtype: float64

In [24]:
#Readmission rate by gender. 
analysis_df.groupby("gender")["is_readmitted_30"].mean()

gender
Female             0.112452
Male               0.110615
Unknown/Invalid    0.000000
Name: is_readmitted_30, dtype: float64

In [25]:
#Readmission by age 
analysis_df.groupby("age")["is_readmitted_30"].mean().sort_index()

age
[0-10)      0.018634
[10-20)     0.057887
[20-30)     0.142426
[30-40)     0.112318
[40-50)     0.106040
[50-60)     0.096662
[60-70)     0.111284
[70-80)     0.117731
[80-90)     0.120835
[90-100)    0.110992
Name: is_readmitted_30, dtype: float64

In [26]:
# Creating a midpoint range for cleaner python analysis. 
age_map = {
    "[0-10)": 5, "[10-20)": 15, "[20-30)": 25, "[30-40)": 35,
    "[40-50)": 45, "[50-60)": 55, "[60-70)": 65, "[70-80)": 75,
    "[80-90)": 85, "[90-100)": 95
}

analysis_df["age_mid"] = analysis_df["age"].map(age_map)
analysis_df[["age", "age_mid"]].head()

       age  age_mid
0   [0-10)        5
1  [10-20)       15
2  [20-30)       25
3  [30-40)       35
4  [40-50)       45

In [27]:
#Readmission rate by age but cleaner. 
analysis_df.groupby("age_mid")["is_readmitted_30"].mean()

age_mid
5     0.018634
15    0.057887
25    0.142426
35    0.112318
45    0.106040
55    0.096662
65    0.111284
75    0.117731
85    0.120835
95    0.110992
Name: is_readmitted_30, dtype: float64

In [28]:
# Saving the cleaned file for Tableau. 
analysis_df.to_csv("../data/cleaned_readmission_data.csv", index=False)